#!/bin/bash

# Get battery percentage
battery_level=$(cat /sys/class/power_supply/BAT0/capacity)

# Get battery health
battery_health=$(cat /sys/class/power_supply/BAT0/capacity_level)

# Check if battery level is below 20%
if [ $battery_level -lt 20 ]; then
    notify-send "Low Battery" "Power Level: $battery_level%. Battery Health: $battery_health. Please plug in your system"
fi
