return {}
-- return {
--   "nvim-neorg/neorg",
--   lazy = false,
--   version = "*", -- Pin Neorg to the latest stable release
--   config = function()
--     require("neorg").setup {
--       load = {
--         ["core.defaults"] = {},
--         ["core.concealer"] = {},
--         ["core.completion"] = {
--           config = {
--             engine = "nvim-cmp",
--           },
--         },
--         ["core.integrations.nvim-cmp"] = {},
--         ["core.dirman"] = {
--           config = {
--             workspaces = {
--               notes = "~/notes",
--             },
--             default_workspace = "notes",
--           },
--         },
--       },
--     }
--
--     vim.wo.foldlevel = 99
--     vim.wo.conceallevel = 2
--   end,
-- }
