## Colors configuration
[colors.primary]
background = "#050C13"
foreground = "#a7bbc0"

[colors.normal]
black   = "#050C13"
red     = "#124755"
green   = "#354A4E"
yellow  = "#235A68"
blue    = "#47575C"
magenta = "#506A72"
cyan    = "#4E7985"
white   = "#a7bbc0"

[colors.bright]
black   = "#748286"
red     = "#124755"
green   = "#354A4E"
yellow  = "#235A68"
blue    = "#47575C"
magenta = "#506A72"
cyan    = "#4E7985"
white   = "#a7bbc0"
