## Colors configuration
[colors.primary]
background = "#12121b"
foreground = "#e1e9ee"

[colors.normal]
black   = "#12121b"
red     = "#9BD2A4"
green   = "#ABE9B3"
yellow  = "#DCB6F1"
blue    = "#8FD5F3"
magenta = "#ABD9F2"
cyan    = "#CACCFD"
white   = "#e1e9ee"

[colors.bright]
black   = "#9da3a6"
red     = "#9BD2A4"
green   = "#ABE9B3"
yellow  = "#DCB6F1"
blue    = "#8FD5F3"
magenta = "#ABD9F2"
cyan    = "#CACCFD"
white   = "#e1e9ee"
