general {
	hide_cursor = true
	ignore_empty_input = true
	immediate_render = false
	text_trim = true
	fractional_scaling = 2
	fail_timeout = 2000
}
auth {
	pam:enabled = true
	pam:module = hyprlock
	fingerprint:enabled = false
	fingerprint:ready_message = (Scan fingerprint to unlock)
	fingerprint:present_message = Scanning fingerprint
}
background {
    monitor =
    path = ~/Pictures/Wallpapers/947089.jpg
    # path = screenshot
    color = rgba(26, 27, 38, 1.0)
    blur_passes = 3
    blur_size = 5
    noise = 0.01
    contrast = 0.9000
    brightness = 0.8500
    vibrancy = 0.1700
    vibrancy_darkness = 0.0
    zindex = -1
}
input-field {
    monitor =
    size = 265, 40
    outline_thickness = 3
    dots_size = 0.35
    dots_spacing = 0.25
    dots_center = false
    dots_rounding = -2
    dots_fade_time = 200
    dots_text_format = 
    outer_color = rgb(65, 72, 104)
    inner_color = rgb(36, 40, 59)
    font_color = rgb(192, 202, 245)
    font_family = JetBrainsMono NF Bold
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = password
    hide_input = false
    rounding = 2
    check_color = rgb(158, 206, 106)
    fail_color = rgb(247, 118, 142)
    fail_text = invalid credentials
    fail_timeout = 2000
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 0, -25
    halign = center
    valign = center
	zindex = 0
	
	shadow_passes = 3
	shadow_size = 6
	shadow_color = rgb(0, 0, 0)
	shadow_boost = 0.50
}
label {
    monitor =
    text = <span foreground='##c0caf5'>$TIME</span>
    text_align = center
    color = rgb(192, 202, 245)
    font_size = 64
    font_family = JetBrainsMono NF Bold
	rotate = 0
    position = 0, 250
    halign = center
    valign = center
	shadow_passes = 3
	shadow_size = 6
	shadow_color = rgb(0, 0, 0)
	shadow_boost = 1.0
}
# User
label {
    monitor =
    text = <span foreground='##c0caf5'>  <b>$USER</b></span>
    text_align = center
    color = rgb(192, 202, 245)
    font_size = 32
    font_family = JetBrains Mono Bold
    position = 0, 50
    halign = center
    valign = center
	shadow_passes = 3
	shadow_size = 6
	shadow_color = rgb(0, 0, 0)
	shadow_boost = 0.50
}
# Icon
label {
    monitor =
    text = <span foreground='##c0caf5'>  </span>
    text_align = center
    color = rgb(192, 202, 245)
    font_size = 32
    font_family = JetBrainsMono NF Bold
    position = 0, -550
    halign = center
    valign = center
}
