# Shell variables
# Generated by 'wal'
wallpaper='/home/clevrf0x/Pictures/wallpapers/jinx.jpg'

# Special
background='#050C13'
foreground='#a7bbc0'
cursor='#a7bbc0'

# Colors
color0='#050C13'
color1='#124755'
color2='#354A4E'
color3='#235A68'
color4='#47575C'
color5='#506A72'
color6='#4E7985'
color7='#a7bbc0'
color8='#748286'
color9='#124755'
color10='#354A4E'
color11='#235A68'
color12='#47575C'
color13='#506A72'
color14='#4E7985'
color15='#a7bbc0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
