# Shell variables
# Generated by 'wal'
wallpaper='/home/clevrf0x/Pictures/wallpapers/various-os-2-4k.png'

# Special
background='#12121b'
foreground='#e1e9ee'
cursor='#e1e9ee'

# Colors
color0='#12121b'
color1='#9BD2A4'
color2='#ABE9B3'
color3='#DCB6F1'
color4='#8FD5F3'
color5='#ABD9F2'
color6='#CACCFD'
color7='#e1e9ee'
color8='#9da3a6'
color9='#9BD2A4'
color10='#ABE9B3'
color11='#DCB6F1'
color12='#8FD5F3'
color13='#ABD9F2'
color14='#CACCFD'
color15='#e1e9ee'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
